config/routes.rb
Enpit::Application.routes.draw do

  get "race_progresses/show"
  resources :books

  root 'races#top'

  get '/races(.:format)'        => "races#index", :as => :races
  get '/race/:id(.:format)'     => "races#show",  :as => :race

  get '/race/:id/progresses/:date' => "race_progresses#show", :as => :race_progress

  get '/race/:id/result'        => "race_results#show", :as => :race_result

  post '/race/:id/voting_cards' => 'voting_cards#vote', :as => :voting_cards

  post '/race/:race_id/comments' => 'comments#create',   :as => :comments

  get    '/admin'               => "admin#home",        :as => :admin_home
  get    '/admin/login'         => "admin#login"
  get    '/admin/race/list'     => "admin#list_race",   :as => :adm_race
  get    '/admin/race/new'      => "admin#new_race",    :as => :new_race
  post   '/admin/race'          => "admin#create_race"
  get    '/admin/race/edit/:id' => "admin#edit_race",   :as => :edit_race
  put    '/admin/race/:id'      => "admin#update_race"
  patch  '/admin/race/:id'      => "admin#update_race"
  delete '/admin/race/:id'      => "admin#destroy_race"

  get 'races_test/test' => 'races#test'

  get '/auth/:provider' => "sessions#create_developer" unless Rails.env.production? and !ENV['TEST']
  get '/auth/:provider/callback' => "sessions#create"
  get '/logout' => "sessions#destroy", :as => :logout

  get 'rankings/fetch' => "rankings#fetch"

  

end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.erb
<%= form_for(@ranking) do |f| %>
  <% if @ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
      <% @ranking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xml %><br />
    <%= f.text_area :xml %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rankings/edit.html.erb
<h1>Editing ranking</h1>

<%= render 'form' %>

<%= link_to 'Show', @ranking %> |
<%= link_to 'Back', rankings_path %>

app/views/rankings/fetch.html.erb
<%= @result %>

app/views/rankings/index.html.erb
<h1>Listing rankings</h1>

<table>
  <tr>
    <th>Xml</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rankings.each do |ranking| %>
  <tr>
    <td><%= ranking.xml %></td>
    <td><%= link_to 'Show', ranking %></td>
    <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
    <td><%= link_to 'Destroy', ranking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ranking', new_ranking_path %>

app/views/rankings/new.html.erb
<h1>New ranking</h1>

<%= render 'form' %>

<%= link_to 'Back', rankings_path %>

app/views/rankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Xml:</b>
  <%= @ranking.xml %>
</p>


<%= link_to 'Edit', edit_ranking_path(@ranking) %> |
<%= link_to 'Back', rankings_path %>