config/routes.rb
Enpit::Application.routes.draw do

  get "race_progresses/show"
  resources :books

  root 'races#top'

  get '/races(.:format)'        => "races#index", :as => :races
  get '/race/:id(.:format)'     => "races#show",  :as => :race

  get '/race/:id/progresses/:date' => "race_progresses#show", :as => :race_progress

  get '/race/:id/result'        => "race_results#show", :as => :race_result

  post '/race/:id/voting_cards' => 'voting_cards#vote', :as => :voting_cards

  post '/race/:race_id/comments' => 'comments#create',   :as => :comments

  get    '/admin'               => "admin#home",        :as => :admin_home
  get    '/admin/login'         => "admin#login"
  get    '/admin/race/list'     => "admin#list_race",   :as => :adm_race
  get    '/admin/race/new'      => "admin#new_race",    :as => :new_race
  post   '/admin/race'          => "admin#create_race"
  get    '/admin/race/edit/:id' => "admin#edit_race",   :as => :edit_race
  put    '/admin/race/:id'      => "admin#update_race"
  patch  '/admin/race/:id'      => "admin#update_race"
  delete '/admin/race/:id'      => "admin#destroy_race"

  get 'races_test/test' => 'races#test'

  get '/auth/:provider' => "sessions#create_developer" unless Rails.env.production? and !ENV['TEST']
  get '/auth/:provider/callback' => "sessions#create"
  get '/logout' => "sessions#destroy", :as => :logout

  get 'rankings/fetch' => "rankings#fetch"

  

end

app/models/race.rb
class Race < ActiveRecord::Base

  has_many :race_horses, :dependent => :destroy
  has_many :voting_cards, :dependent => :destroy 
  has_many :race_progresses, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_one  :race_result, :dependent => :destroy
  belongs_to :genre
  belongs_to :current_progress, foreign_key: "current_progress_id", class_name: "RaceProgress"
  
  validates :name, :start_date, :end_date, :genre_id,  presence: true
  validates :name, length: {minimum: 3, maximum: 20}
  validates_each :race_horses do |record, attr, horses|
    unless horses.size == 10
      record.errors[attr] << "本を10冊登録してください。"
    end
  end
  validates_each :state do |record, attr, state|
    unless STATES.include? state
      record.errors[attr] << " must in #{STATES.join(', ')}."
    end
  end

  GRADES = {1 => 'GⅠ', 2 => 'GⅡ', 3 => 'GⅢ'}
  STATES = %w{ READY RUNNING END }

  # バッチ処理として呼出される
  def create_progress(the_date)
    olds = race_progresses.select {|p| p.record_date == the_date}
    #olds.each {|o| o.destroy} unless olds.empty?
    prog = RaceProgress.new(record_date: the_date)
    prog.race = self
    prog.calc_order()
    self.race_progresses << prog
    save!
  end

  def progress(the_date = :last)
    if the_date == :current
      if current_progress
      then return current_progress
      else return RaceProgress.new(race: self)
      end
    elsif the_date == :last
      return race_progresses.sort.last
    else
      return race_progresses.find {|p| p.record_date == the_date}
    end
  end

  def create_result()
    self.race_result = RaceResult.new(race_progress: progress(:current), race: self)
    # レース状態をRUNNING → ENDに変更する
    self.state = 'END'
    save!
  end

  # バッチ処理として呼出される
  def start
    puts "race start: {name: #{name}, start_date: #{start_date}, end_date: #{end_date}}"

    # レース状態をREADY → RUNNINGに変更する
    state = "RUNNING"
    # 蓄積されている経過状況を、record_dateでソートして取得する
    progs = race_progresses.sort
    # トータル経過をセットする
    self.num_of_progs = progs.size
    # 更新頻度を計算する
    interval = (end_date - start_date) / progs.size.to_f
    # レース経過を計算した頻度でスイッチする
    progs.each_with_index do |prog, i|
      self.current_progress = prog
      self.point_of_progs = i + 1
      save!
      sleep interval
    end
    # レースを終了(確定)する
    create_result()
    # 払い戻す
    voting_cards.each {|card| card.payback()}

    puts "race end:   {name: #{name}, start_date: #{start_date}, end_date: #{end_date}}"
  end

  # for testing
  def _result
    result = RaceResult.new
    prog = progress(:last)
    result.race_progress = prog
    result.race = self
    result
  end

end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  
  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end
  
  def top
    @users = User.find(:all, :order => "point DESC")
    @genres = Genre.all
    @races_id = Race.all;
    @accept_races = Race.find(:all, :conditions => ['end_date >= ?' , Date.today.to_datetime])
    @end_races = Race.find(:all, :conditions => ['end_date < ?' , Date.today.to_datetime])
    render "races/top"
  end

  # GET /races/1
  def show
    if Race.find_by_id(params[:id])
      @race = Race.find(params[:id], :include => :race_horses)
      if current_user
        @card = VotingCard.find_by(:race_id => @race.id, :user_id => current_user.id)
        flash[:notice] = "あなたの投票内容です。" if @card
      end
    else
      redirect_to :controller => 'races' , :action => 'index'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

end

app/helpers/races_helper.rb
module RacesHelper

  #出走の色付け -> show
  def horse_number_colors(number)
    horseNumberColors = ['white','black','red','blue','yellow','green','orange','pink','skyblue','limegreen']
    currentColor = nil
    if horseNumberColors.size - 1 >= number
      currentColor = horseNumberColors[number]
    end
    return currentColor
  end
  
  #出走馬の色付け
  def search_expectation( number )
    return VoteItem::EXPECTATION[number]
  end
  
  #縦書き表示 -> show
  def row_text(text)
    result = ''
    textArr = text.split(//)
    textArr.each do |s|
      s = s === "ー" ? "｜" : s ;
      result += s + '<br />'
    end
    return result
  end
  
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.number_field :grade %>
  </div>
  <div class="field">
    <%= f.label :etype %><br>
    <%= f.text_field :etype %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div id="button-field" class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/_race_table.html.erb
<div class="cf">
<div id="race-table" style="width:915px;float:left">
<table id="vote-table">
	<thead>
		<tr>
		<% @race.race_horses.reverse_each do |horse| %>
			<th style="color: <%= horse.horse_color.text_color %>; background-color: <%= horse.horse_color.background_color %>"><%= horse.horse_no %></th>
		<% end %>
			<!-- ここまで -->
			<th>　</th>
		</tr>
	</thead>
	<tbody>
		<tr>
		<% @race.race_horses.reverse_each do |race_horse| %>
      <% book = race_horse.book %>
      <% image_url = book.medium_image_url || book.large_image_url || book.small_image_url %>
			<td><%= link_to image_tag(image_url, size: '60x90', alt: "image"), book.item_url %></td>
		<% end %>
			<td class="title" rowspan="2"><%= row_text("書籍").html_safe %></td>
		</tr>
		<tr>
		<% @race.race_horses.reverse_each do |race_horse| %>
			<td><%= row_text(race_horse.book.title).html_safe %></td>
		<% end %>
		</tr><!-- 書籍 -->
		<tr>
		<% @race.race_horses.reverse_each do |race_horse| %>
			<td><%= row_text(race_horse.book.author).html_safe %></td>
		<% end %>
			<td class="title"><%= row_text("著者").html_safe %></td>
		</tr><!-- 著者 -->
		<tr>
		<% @race.race_horses.reverse_each do |race_horse| %>
			<td><%= row_text(race_horse.book.publisher).html_safe %></td>
		<% end %>
			<td class="title"><%= row_text("出版社").html_safe %></td>
		</tr><!-- 出版社 -->
		<tr>
		<% @race.race_horses.reverse_each do |race_horse| %>
			<td><%= race_horse.odds %></td>
    <% end %>
			<td class="title"><%= row_text("オッズ").html_safe %></td>
		</tr><!-- オッズ -->
    <% if current_user %>
    <tr>
  		<% unless @card %>
  			<% @race.race_horses.reverse_each do |horse| %>
  			  <td id="vote_item_<%= horse.id %>" class="vote_item">
            <%= radio_button "vote_item", 'horse', horse.id, {:checked => false, :class => 'vote_item_radio'}%>
  			  </td>
  			<% end %>
  		<% else %>
  			<% @race.race_horses.reverse_each do |horse| %>
  			<td>
          <% vote_item = @card.vote_items.find {|item| item.race_horse == horse} %>
          <% if vote_item %>
            <%= radio_button "vote_item", 'horse', horse.id, {:checked => false, :class => 'vote_item_radio'}%>
          <% end %>
  			</td>
  			<% end %>
  		<% end %>
			<td class="title"><%= row_text("選択").html_safe %></td>
		</tr>
    <% end %>
	</tbody>
</table>
</div>
<div id="race-caption" style="background:#FFF;width:61px;border:4px solid #333;border-left:none;float:left">
    <h3 style="font-weight:bold;text-align:center;font-size:140%;padding-top:10px;"><%= (@race.genre.name[0,3]) %></h3>
	<div style="font-weight:bold;background:#000;color:#FFF;font-size:250%;text-align:center;padding:10px;"><%= (@race.id.to_s) %></div>
	<h4 style="text-align:center;font-weight:bold;font-size:130%">発走</h4>
	<h4 style="text-align:center;font-weight:bold;font-size:110%"><%= @race.start_date.strftime("%H:%M") %></h4>
	<h3 style="font-weight:bold;text-align:center;font-size:150%;padding:10px;"> <%= row_text(@race.name).html_safe %> <%= "(" + Race::GRADES[@race.grade] +")"%></h3>
</div>
<script type="text/javascript" charset="utf-8">
$(window).load(function(){$('#race-caption').height($('#vote-table').height());});
</script>
</div>
<% if current_user %>
  <% unless @card %>
  <div id="vote_amount">
    <span>投票金額</span>
    <%= number_field "vote_item", "amount", {disabled: true, required: true, min: 1}%>
    <span>Zeny</span>
  </div>
  <div class="submit lib-aside-mTop" style="text-align: center">
	    <button id="submit_vote" class="lib-btn-black lib-button-large" style="font-size:200%;" disabled="disabled">投票する</button>
	    <%= link_to "戻　る" , root_path , :class => "lib-btn lib-button-large" , :style => "margin-left:20px;font-size:200%;" %>

      <hr style="margin-top: 20px;">

	    <input type="hidden" id="user_zeny" name="user_zeny" value="<%= current_user.point %>" />
	    <div id="my-status" class="cf">
	    	<h2 style="font-weight:bold;font-size:130%;line-height:4em;text-align:left"><%= current_user.name %>さんのステータス</h2>
	    	<ul style="width:220px;float:left;border:2px solid #000">
	    		<li style="padding:6px 0 10px 0"><%= image_tag('contents/no_image.png') %></li>
	    		<li style="background:#333;color:#FFF;font-size:110%;padding:10px;font-weight:bold;">
	    			<p><%= current_user.name %>さんのお財布</p>
	    			<p><%= number_with_delimiter current_user.point %> ゼニー</p>
	    		</li>
	    	</ul>
	    	<ul style="margin-left:20px;width:600px;float:left;">
	    		<li>
	    			<ul class="cf">
	    				<li class="zeny-title">投票ゼニー</li>
	    				<li class="zeny-display">
	    					<span id="wagar-display" class="zeny-big">0</span>ゼニー
	    				</li>
	    			</ul>
	    		</li>
	    		<li class="lib-aside-mTop">
	    			<ul class="cf">
	    				<li class="zeny-title">残りのゼニー</li>
	    				<li class="zeny-display">
	    					<span id="remaining-display" class="remining-zeny-big">
	    						<%= number_with_delimiter current_user.point %>
	    					</span>ゼニー
	    				</li>
	    			</ul>
	    		</li>
	    	</ul>
	    </div>
 	<% else %>
	    <%= link_to "戻　る" , root_path , :class => "lib-btn lib-button-large" , :style => "margin-left:20px;font-size:200%;" %>
  <% end %>
<%else %>
  <div style="text-align: center">
  <p id="please_login">投票するにはログインしてください。</p>
  <%= link_to "戻　る" , root_path , :class => "lib-btn lib-button-large" , :style => "margin-left:20px;font-size:200%;" %>
  </div>
<% end %>
</div>

<style type="text/css" media="screen">
#my-status {
	margin-top:40px;
	margin-left:40px;
}
#my-status .zeny-title {
	color:#FFF;
	background:#333;
	font-weight:bold;
	font-size:130%;
	border-top:2px solid #000;
	border-bottom:2px solid #000;
	border-left:2px solid #000;
	width:200px;
	padding:33px 10px;
	text-align:left;
	float:left;
}
#my-status .zeny-display {
	color:#333;
	font-weight:bold;
	border:2px solid #000;
	font-size:130%;
	padding:32px 10px;
	text-align:left;
	width:352px;
	float:left;
}
#my-status .zeny-big {
	color:#FF6600;
	font-size:140%;
	margin-right:10px;
}
#my-status .remining-zeny-big {
	color:#FF3300;
	font-size:140%;
	margin-right:10px;
}
#race-table td {width:97px;}
.title td {width:10px;}
.require {margin-top:10px;margin-bottom:5px;}
label.valid-message {
	color:#FF7700;
	background:#FFF;
	font-weight:bold;
	line-height:2.2em;
	padding:0 3px;
	border-radius:5px;
	border:2px solid #FF7700;
	display:block;
	position: relative;
}
label.valid-ok {
	color:#FFF;
	background:#FF7700;
	font-weight:bold;
	line-height:2.2em;
	padding:0 3px;
	border-radius:5px;
	border:2px solid #FF7700;
	display:block;
	position: relative;
}
label.valid-none {
  color: transparent;
	background:transparent;
	font-weight:bold;
	line-height:2.2em;
	padding:0 3px;
	border-radius:5px;
	border:2px solid transparent;
	display:block;
	position: relative;
}
label.valid-error{
	color:#FFF;
	background:#FF7700;
}
label.valid-success{
	color:#FF6600;
	background: #FAFAFA;
	border:2px solid #999;
}
#vote_amount {
  margin-top: 20px;
  text-align: center;
}
#vote_amount span {
  font-size: 180%;
  margin: 0 10px;
}
#vote_item_amount {
  font-size: 200%;
}
#please_login {
  margin: 20px 0px 30px 0px;
  font-size: 200%;
}
</style>

app/views/races/_top_accept_race.erb
<div id="race-state-vote">
<% @accept_races.each do |race| %>
	<dl class="cf" data-id="<%= race.id %>">
		<dt class="image">
		<% if !race.race_horses[0].book.nil? %>
			<%= image_tag(race.race_horses[0].book.medium_image_url) %>
		<% else %>
			<%= image_tag('contents/no_image.png', :style => 'width:auto;height:120px') %>
		<% end %>
		</dt>
		<dd class="title">
			<h3>
			<% if race.race_result and race.race_result.id %>
				<%= link_to race.name, race_result_path(race.id) %>
			<% else %>
				<% if current_user and current_user.voting_cards.find {|c| c.race == race} and !race.race_progresses.empty? %>
					<%= link_to race.name, race_progress_path(race.id, :last) %>
				<% else %>
					<%= link_to race.name, race %>
				<% end %>
			<% end %>
			</h3>
		</dd><!--　タイトル名 -->
		<dd class="participant">
			参加者<span><%= race.voting_cards.size %></span>名
		</dd><!--　ジャンル名 -->
		<dd class="election-date">
			<p>開始日時：<%= race.start_date.strftime("%m-%d %H:%M") %></p>
			<p>終了日時：<%= race.end_date.strftime("%m-%d %H:%M") %></p>					
		</dd><!-- 投票受付日から締日 -->
		<dd style="padding:10px;text-align: center;">
		<% if race.race_result and race.race_result.id %>
			<%= link_to 'レースを見る・投票する！', race_result_path(race.id), :class => 'lib-btn lib-button-small',:style => 'color:black' %>
		<% else %>
			<% if current_user and current_user.voting_cards.find {|c| c.race == race} and !race.race_progresses.empty? %>
				<%= link_to 'レースを見る・投票する！', race_progress_path(race.id, :last), :class => 'lib-btn lib-button-small',:style => 'color:black' %>
			<% else %>
				<%= link_to 'レースを見る・投票する！', race, :class => 'lib-btn lib-button-small',:style => 'color:black' %>
			<% end %>
		<% end %>
		</dd>
	</dl>
<% end %>
</div>

app/views/races/_top_end_race.erb
<div id="race-state-end" style="display:none">
<% @end_races.each do |race| %>
	<dl class="cf" data-id="<%= race.id %>">
		<dt class="image">
			<% if !race.race_horses[0].book.nil? %>
				<%= image_tag(race.race_horses[0].book.medium_image_url) %>
			<% else %>
				<%= image_tag('contents/no_image.png', :style => 'width:auto;height:120px') %>
			<% end %>
		</dt>
		<dd class="title">
			<h3>
          	<% if race.race_result and race.race_result.id %>
				<%= link_to race.name, race_result_path(race.id) %>
           	<% else %>
 				<% if current_user and current_user.voting_cards.find {|c| c.race == race} and !race.race_progresses.empty? %>
					<%= link_to race.name, race_progress_path(race.id, :last) %>
				<% else %>
					<%= link_to race.name, race %>
				<% end %>
			<% end %>
			</h3>
		</dd><!--　タイトル名 -->
		<dd class="participant">
			参加者<span><%= race.voting_cards.size %></span>名
		</dd><!--　ジャンル名 -->
		<dd class="election-date">
			<p>開始日時：<%= race.start_date.strftime("%m-%d %H:%M") %></p>
			<p>終了日時：<%= race.end_date.strftime("%m-%d %H:%M") %></p>					
		</dd><!-- 投票受付日から締日 -->
		<dd style="padding:10px;text-align: center;">
		<% if race.race_result and race.race_result.id %>
			<%= link_to 'レース結果を見る！', race_result_path(race.id), :class => 'lib-btn lib-button-small',:style => 'color:black' %>
		<% else %>
			<% if current_user and current_user.voting_cards.find {|c| c.race == race} and !race.race_progresses.empty? %>
				<%= link_to 'レース結果を見る！', race_progress_path(race.id, :last), :class => 'lib-btn lib-button-small',:style => 'color:black' %>
			<% else %>
				<%= link_to 'レース結果を見る！', race, :class => 'lib-btn lib-button-small',:style => 'color:black' %>
			<% end %>
		<% end %>
		</dd>
	</dl>
	<% end %>
</div>

app/views/races/edit.html.erb
<h1>Editing race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<h1>ログインしてください。またはレースがありません。</h1>
<%= link_to 'トップページに戻る', root_path %>
<br>

app/views/races/new.html.erb
<h1>New race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<!-- レース　詳細ページ　仮配置  -->
<% if @card and @card.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@card.errors.count, "error") %> prohibited this book from being saved:</h2>
    <ul>
    <% @card.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<!-- エラーメッセージ。TODO 協調表示する -->
<% if flash[:error] %>
  <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
<% end %>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<h2 style="display:block;background:#333;padding:10px;color:#FFF;font-size:190%;font-weight:bold;border-radius:5px 5px 0 0">
	<i class="icon-trophy icon-margin-right" style="font-size:120%;font-weight:normal;color: yellow"></i>
	出走馬一覧
</h2>
<!-- ここに form タグを挿入すること -->
<div id="rece-list">
<% unless @card %>
  <%= form_tag voting_cards_path(@race), id: 'vote-form' do %>
    <%= render 'races/race_table' %>
  <% end %>
<% else %>
  <%= render 'races/race_table' %>
<% end %>
</div>

app/views/races/test.html.erb
<!-- レース　詳細ページ　仮配置  -->
<h2 style="display:block;background:#333;padding:10px;color:#FFF;font-size:190%;font-weight:bold;border-radius:5px 5px 0 0">
	<i class="icon-trophy icon-margin-right" style="font-size:120%;font-weight:normal;color: yellow"></i><%= @raceTest.name %>
</h2>
<!-- ここに form タグを挿入すること -->
<table id="vote-table">
	<thead>
		<tr>
		<% for i in 1..@raceTest.race_horses.size %>
			<th class="blue"><%= i %></th>
		<% end %>
			<!-- ここまで -->
			<th>　</th>
		</tr>
	</thead>
	<tbody>
		<tr>
		<% for race_horse in @raceTest.race_horses %>
			<td><%= race_horse.book.title %></td>
		<% end %>
			<td>著名</td>
		</tr><!--　著名 -->
		<tr>
		<% for race_horse in @raceTest.race_horses %>
			<td><%= race_horse.book.author %></td>
		<% end %>
			<td>著者</td>
		</tr><!-- 著者 -->
		<tr>
		<% for race_horse in @raceTest.race_horses %>
			<td><%= race_horse.book.publisher %></td>
		<% end %>
			<td>出版舎</td>
		</tr><!-- 出版社 -->
		<tr>
		<% for i in 1..@raceTest.race_horses.size %>
			<td>
				<select name="" id="" class="lib-select lib-select-small">
					<option value=""> </option>
					<option value="">◎本命</option>
					<option value="">○？？</option>
					<option value="">▲？？</option>
				</select>
			</td>
		<% end %>
			<td>選択</td>
		</tr>
	</tbody>
</table>
<%= debug(@raceTest.race_horses[0].book) %>
<div class="submit lib-aside-mTop" style="text-align: center">
	<button class="lib-btn-black lib-button-large" style="font-size:200%;">投票する</button>
	<button class="lib-btn lib-button-large" style="margin-left:20px;font-size:200%;">戻　る</button>
</div>

app/views/races/top.html.erb
<div id="races-list">
	<div id="race-list-menu" class="menu">
		<ul class="cf">
			<li data-id="race-state-vote" class="active">投票受付中</li>
			<li data-id="race-state-during">レース中</li>
			<li data-id="race-state-end">レース終了</li>
		</ul>
	</div>
	<div id="race-list-content" class="list cf">
		<%= render 'races/top_accept_race' %>
		<%= render 'races/top_end_race' %>
	</div>
</div><!-- race-list -->

<div id="race-list-dialog">
	<div class="race-dialog-header" style="text-indent: 15px">詳細</div>
	<h3 style="font-size:130%;font-weight:bold;padding:10px 15px 5px 15px;">出場リスト</h3>
	<div class="race-dialog-contents cf"></div>
</div><!-- race-list-dialog -->

<div id="aside">
<% if current_user %>
	<section class="aside-list">
		<h2>ユーザー情報</h2>		
		<ul>
			<li style="text-align: center;"><%= image_tag('contents/no_image.png') %></li>
			<li style="border-top:2px solid #333;padding:5px;">
				<strong><%= current_user.name %></strong>さん
			</li>
			<li style="border-top:2px solid #333;padding:5px;">
				現在のZeny：<span style="color:#ff6600;font-weight:bold;font-size:160%;"><%= current_user.point %></span>Zeny
			</li>
			<li style="border-top:2px solid #333;padding:5px">
				参加中レース数：<%= VotingCard.find(:all, :conditions => ["user_id = ?",current_user.id]).count %>
			</li>
			<li style="border-top:2px solid #333;padding:5px">
				終了レース数：<% VotingCard.find(:all, :conditions => ['user_id = ? AND payout IS NOT ?', current_user.id, nil]).count %>
			</li>
		</ul>
	</section>
<% end %>			
</div><!-- aside -->

<% @races_id.each do |race| %>
<input type="hidden" class="race_id_list" value="<%= race.id %>" />
<% end %>