config/routes.rb
Enpit::Application.routes.draw do

  get "race_progresses/show"
  resources :books

  root 'races#top'

  get '/races(.:format)'        => "races#index", :as => :races
  get '/race/:id(.:format)'     => "races#show",  :as => :race

  get '/race/:id/progresses/:date' => "race_progresses#show", :as => :race_progress

  get '/race/:id/result'        => "race_results#show", :as => :race_result

  post '/race/:id/voting_cards' => 'voting_cards#vote', :as => :voting_cards

  post '/race/:race_id/comments' => 'comments#create',   :as => :comments

  get    '/admin'               => "admin#home",        :as => :admin_home
  get    '/admin/login'         => "admin#login"
  get    '/admin/race/list'     => "admin#list_race",   :as => :adm_race
  get    '/admin/race/new'      => "admin#new_race",    :as => :new_race
  post   '/admin/race'          => "admin#create_race"
  get    '/admin/race/edit/:id' => "admin#edit_race",   :as => :edit_race
  put    '/admin/race/:id'      => "admin#update_race"
  patch  '/admin/race/:id'      => "admin#update_race"
  delete '/admin/race/:id'      => "admin#destroy_race"

  get 'races_test/test' => 'races#test'

  get '/auth/:provider' => "sessions#create_developer" unless Rails.env.production? and !ENV['TEST']
  get '/auth/:provider/callback' => "sessions#create"
  get '/logout' => "sessions#destroy", :as => :logout

  get 'rankings/fetch' => "rankings#fetch"

  

end

app/views/layouts/_detail.html.erb
<!-- レース　詳細ページ　仮配置  -->
<h2 style="display:block;background:#333;padding:10px;color:#FFF;font-size:190%;font-weight:bold;border-radius:5px 5px 0 0">
	<i class="icon-trophy icon-margin-right" style="font-size:120%;font-weight:normal;color: yellow"></i>G1なんとか杯
</h2>
<!-- ここに form タグを挿入すること -->

<table id="vote-table">
	<thead>
		<tr>
			<!-- ループ 10回 -->
			<th class="blue">10</th>
			<!-- ここまで -->
			<th>　</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<!-- ループ  10回 -->
			<td><?php echo rowText("はじめての楽しいヨガ4週間プログラム") ?></td>
			<!-- ここまで　-->
			<td>著名</td>
		</tr><!--　著名 -->
		<tr>
			<td>梅澤志乃</td>
			<td>著者</td>
		</tr><!-- 著者 -->
		<tr>
			<!-- ループ 10回  -->
			<td class="double-circle">◎</td>
			<!-- ここまで　-->
			<td>本命予測</td>
		</tr><!-- 予測 -->
		<tr>
			<!-- ループ 10回 -->
			<td>中央経済社</td>
			<!--ここまで　-->
			<td>出版舎</td>
		</tr><!-- 出版社 -->
		<tr>
			<!-- ループ 10回 -->
			<td>
				<select name="" id="" class="lib-select lib-select-small">
					<option value=""> </option>
					<option value="">◎本命</option>
					<option value="">○？？</option>
					<option value="">▲？？</option>
				</select>
			</td>
			<!-- ここまで　-->
			<td>選択</td>
		</tr>
	</tbody>
</table>

<div class="submit lib-aside-mTop" style="text-align: center">
	<button class="lib-btn-black lib-button-large" style="font-size:200%;">投票する</button>
	<button class="lib-btn lib-button-large" style="margin-left:20px;font-size:200%;">戻　る</button>
</div>

<!-- ここにフォームの〆タグ -->

app/views/layouts/_footer.html.erb
<div id="page-top" class="cf">
	<a href="#">
		<i class="icon-arrow-up icon-margin-right"></i>先頭に戻る
	</a>
</div><!-- //page-top -->
<div id="footer">
	<div class="inner">
		<article class="footer-head cf" style="display:none">
			<ul class="summary">
				<li class="lib-box">
					<h3>(仮)ぶっく競馬</h3>
					<p>みんなで本を投票して当選するか予測するサイトです。</p>
					<p>当たれば、当たるほどお得なポイントが溜まります！！</p>
					<p>もしかしたら、楽天から・・・</p>
					<p>何か素敵なプレゼントも？</p>
				</li>
				<li class="logo-image">
					<%= image_tag 'footer/logo.png', alt: '' %>
				</li>
			</ul>
			<div id="sitemap01" class="cf">
				<h3>
					<i class="icon-collapse icon-margin-right"></i>
					コンテンツ
				</h3>
				<ul>
					<li><a href="#">ホーム</a></li>
					<li><a href="#">ログイン</a></li>
					<li><a href="#">初めての方へ</a></li>
					<li><a href="#">投票する</a></li>
				</ul>
			</div><!-- sitemap01 -->
			<div id="sitemap02" class="cf">
				<h3>
					<i class="icon-collapse icon-margin-right"></i>
					カテゴリー
				</h3>
				<ul>
					<li><a href="#"><span>小説・エッセイ</span></a></li>
					<li><a href="#"><span>アライトノベル</span></a></li>
					<li><a href="#"><span>ボーイズラブ（BL）</span></a></li>
					<li><a href="#"><span>文庫</span></a></li>
					<li><a href="#"><span>新書</span></a></li>
					<li><a href="#"><span>美容・暮らし・健康・料理 </span></a></li>
					<li><a href="#"><span>絵本・児童書・図鑑</span></a></li>
					<li><a href="#"><span>ホビー・スポーツ・美術</span></a></li>
					<li><a href="#"><span>旅行・留学・アウトドア</span></a></li>
					<li><a href="#"><span>温泉</span></a></li>
					<li><a href="#"><span>鉄道の旅</span></a></li>
				</ul>
				<ul>
					<li><a href="#"><span>テーマパーク</span></a></li>
					<li><a href="#"><span>ガイドブック</span></a></li>
					<li><a href="#"><span>地図</span></a></li>
					<li><a href="#"><span>紀行・旅行エッセイ</span></a></li>
					<li><a href="#"><span>留学・海外赴任</span></a></li>
					<li><a href="#"><span>旅行主任者</span></a></li>
					<li><a href="#"><span>釣り</span></a></li>
					<li><a href="#"><span>キャンプ</span></a></li>
					<li><a href="#"><span>その他</span></a></li>
					<li><a href="#"><span>ビジネス・経済・就職</span></a></li>
					<li><a href="#"><span>語学・学習参考書</span></a></li>
				</ul>
				<ul>
					<li><a href="#"><span>資格・検定</span></a></li>
					<li><a href="#"><span>科学・医学・技術</span></a></li>
					<li><a href="#"><span>パソコン・システム開発</span></a></li>
					<li><a href="#"><span>人文・思想・社会</span></a></li>
					<li><a href="#"><span>漫画（コミック）</span></a></li>
					<li><a href="#"><span>写真集・タレント</span></a></li>
					<li><a href="#"><span>エンタメ・ゲーム</span></a></li>
					<li><a href="#"><span>楽譜</span></a></li>
					<li><a href="#"><span>付録付き</span></a></li>
					<li><a href="#"><span>バーゲン本</span></a></li>
				</ul>
			</div><!-- // sitemap02 -->
		</article><!-- // footer-head -->
		<article class="copyright">
			CopyRight 2013 AIIT enpit Team HackyandRocky.
		</article><!-- // copyright -->
	</div><!-- //inner -->
</div><!-- //footer -->

app/views/layouts/_header.html.erb
<div id="header">
	<div class="top">
		<div class="top-article cf">
			<div class="top-logo">
				<h1><i class="icon-book"></i><%= link_to "ぶっく競馬" , root_path %></h1>
			</div>
			<div class="top-login">
        <% if current_user %>
				  <span>ようこそ　<i class="icon-user"></i><%= current_user.name %> さん｜</span>
          <%= link_to 'ログアウト', logout_path %>
        <% else %>
				  <%= link_to 'Facebookでログイン', '/auth/facebook' %>
        <% end %>
			</div>
		</div>
	</div><!-- // top -->
</div><!-- // header -->


app/views/layouts/_top_page_parts.html.erb
<div id="top-contents">
	<div class="gallery">
		<div class="gallery-list">
			<ul>
				<li>
					<%= image_tag('gallery/demos2.png', alt: '') %>
				</li>
			</ul>
		</div>
	</div><!-- // gallery -->
	<div class="search"style="display:none">
		<ul class="inner">
			<li>
				<h3><i class="icon-paste icon-margin-right"></i>レースを探す</h3>
				<select name="hoge" id="hoge" class="lib-select">
					<option value="">選択してください</option>
				</select>
				<select name="hoge2" id="hoge2" class="lib-select">
					<option value="">選択してください</option>
				</select>
				<input type="text" name="" id="" class="lib-input lib-input-width-medium" />
				<button class="lib-btn-black">検索</button>
			</li>
		</ul>
	</div><!-- // search -->
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>ブック競馬管理ページ</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= stylesheet_link_tag    "bootstrap/bootstrap.css" %>
    <%= stylesheet_link_tag    "bootstrap/theme.css" %>
    <%= stylesheet_link_tag    "font-awesome/font-awesome.css" %>

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!-- Demo page code -->

<style type="text/css">
input[type="text"] ,input[type="checkbox"] , textarea ,select {
	padding:0;
	margin:0;
	height:auto;
	color: #333;
	width:auto;
	background: #fff;
	zoom: 1;
}
.brand .first {
    color: #ccc;
    font-style: italic;
}
.brand .second {
    color: #fff;
    font-weight: bold;
}
</style>

  <body class=""> 
    <div class="navbar">
        <div class="navbar-inner">
                <ul class="nav pull-right">
                    <li id="fat-menu" class="dropdown">
                        <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-user"></i> スニーカー
                            <i class="icon-caret-down"></i>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a tabindex="-1" href="#">My Account</a></li>
                            <li class="divider"></li>
                            <li><a tabindex="-1" class="visible-phone" href="#">Settings</a></li>
                            <li class="divider visible-phone"></li>
                            <li><a tabindex="-1" href="sign-in.html">Logout</a></li>
                        </ul>
                    </li>
                    
                </ul>
                <%= link_to raw('<span class="first">競馬</span> <span class="second">ブック</span>'), admin_home_path , class: "brand"%>
        </div>
    </div>
    
    <div class="sidebar-nav">
        <a href="#race-menu" class="nav-header" data-toggle="collapse"><i class="icon-briefcase"></i>レース管理<i class="icon-chevron-up"></i></a>
        <ul id="race-menu" class="nav nav-list collapse">
        	<li><%= link_to 'レース登録', new_race_path %></li>
        	<li><%= link_to 'レース検索・編集', adm_race_path %></li>
        </ul>

        <a href="#act-menu" class="nav-header" data-toggle="collapse"><i class="icon-legal"></i>アカウント管理<i class="icon-chevron-up"></i></a>
        <ul id="act-menu" class="nav nav-list collapse">
        	<li><a href="">アカウントの編集</a></li>
        	<li><a href="">アカウントの確認</a></li>
        </ul>
        
    </div>

    <div class="content">

      <%= yield %>

      <footer>
        <p>&copy; 2013 <a href="http://www.portnine.com" target="_blank">hacky and rocky</a></p>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enpit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">

<%= render 'layouts/header' %>
<% if params[:controller]+params[:action] == "racestop" %>
<%= render 'layouts/top_page_parts' %>
<% end %>
<div id="contents" class="cf">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45385114-1', 'denka.herokuapp.com');
  ga('send', 'pageview');

</script>
</body>
</html>